# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yannherklotz/Github/Arider

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yannherklotz/Github/Arider

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yannherklotz/Github/Arider/CMakeFiles /home/yannherklotz/Github/Arider/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yannherklotz/Github/Arider/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named arider

# Build rule for target.
arider: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arider
.PHONY : arider

# fast build rule for target.
arider/fast:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/build
.PHONY : arider/fast

src/arider.o: src/arider.cpp.o

.PHONY : src/arider.o

# target to build an object file
src/arider.cpp.o:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/arider.cpp.o
.PHONY : src/arider.cpp.o

src/arider.i: src/arider.cpp.i

.PHONY : src/arider.i

# target to preprocess a source file
src/arider.cpp.i:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/arider.cpp.i
.PHONY : src/arider.cpp.i

src/arider.s: src/arider.cpp.s

.PHONY : src/arider.s

# target to generate assembly for a file
src/arider.cpp.s:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/arider.cpp.s
.PHONY : src/arider.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/glsl_program.o: src/glsl_program.cpp.o

.PHONY : src/glsl_program.o

# target to build an object file
src/glsl_program.cpp.o:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/glsl_program.cpp.o
.PHONY : src/glsl_program.cpp.o

src/glsl_program.i: src/glsl_program.cpp.i

.PHONY : src/glsl_program.i

# target to preprocess a source file
src/glsl_program.cpp.i:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/glsl_program.cpp.i
.PHONY : src/glsl_program.cpp.i

src/glsl_program.s: src/glsl_program.cpp.s

.PHONY : src/glsl_program.s

# target to generate assembly for a file
src/glsl_program.cpp.s:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/glsl_program.cpp.s
.PHONY : src/glsl_program.cpp.s

src/image_loader.o: src/image_loader.cpp.o

.PHONY : src/image_loader.o

# target to build an object file
src/image_loader.cpp.o:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/image_loader.cpp.o
.PHONY : src/image_loader.cpp.o

src/image_loader.i: src/image_loader.cpp.i

.PHONY : src/image_loader.i

# target to preprocess a source file
src/image_loader.cpp.i:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/image_loader.cpp.i
.PHONY : src/image_loader.cpp.i

src/image_loader.s: src/image_loader.cpp.s

.PHONY : src/image_loader.s

# target to generate assembly for a file
src/image_loader.cpp.s:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/image_loader.cpp.s
.PHONY : src/image_loader.cpp.s

src/io_manager.o: src/io_manager.cpp.o

.PHONY : src/io_manager.o

# target to build an object file
src/io_manager.cpp.o:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/io_manager.cpp.o
.PHONY : src/io_manager.cpp.o

src/io_manager.i: src/io_manager.cpp.i

.PHONY : src/io_manager.i

# target to preprocess a source file
src/io_manager.cpp.i:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/io_manager.cpp.i
.PHONY : src/io_manager.cpp.i

src/io_manager.s: src/io_manager.cpp.s

.PHONY : src/io_manager.s

# target to generate assembly for a file
src/io_manager.cpp.s:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/io_manager.cpp.s
.PHONY : src/io_manager.cpp.s

src/pico_png.o: src/pico_png.cpp.o

.PHONY : src/pico_png.o

# target to build an object file
src/pico_png.cpp.o:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/pico_png.cpp.o
.PHONY : src/pico_png.cpp.o

src/pico_png.i: src/pico_png.cpp.i

.PHONY : src/pico_png.i

# target to preprocess a source file
src/pico_png.cpp.i:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/pico_png.cpp.i
.PHONY : src/pico_png.cpp.i

src/pico_png.s: src/pico_png.cpp.s

.PHONY : src/pico_png.s

# target to generate assembly for a file
src/pico_png.cpp.s:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/pico_png.cpp.s
.PHONY : src/pico_png.cpp.s

src/sprite.o: src/sprite.cpp.o

.PHONY : src/sprite.o

# target to build an object file
src/sprite.cpp.o:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/sprite.cpp.o
.PHONY : src/sprite.cpp.o

src/sprite.i: src/sprite.cpp.i

.PHONY : src/sprite.i

# target to preprocess a source file
src/sprite.cpp.i:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/sprite.cpp.i
.PHONY : src/sprite.cpp.i

src/sprite.s: src/sprite.cpp.s

.PHONY : src/sprite.s

# target to generate assembly for a file
src/sprite.cpp.s:
	$(MAKE) -f CMakeFiles/arider.dir/build.make CMakeFiles/arider.dir/src/sprite.cpp.s
.PHONY : src/sprite.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... arider"
	@echo "... src/arider.o"
	@echo "... src/arider.i"
	@echo "... src/arider.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/glsl_program.o"
	@echo "... src/glsl_program.i"
	@echo "... src/glsl_program.s"
	@echo "... src/image_loader.o"
	@echo "... src/image_loader.i"
	@echo "... src/image_loader.s"
	@echo "... src/io_manager.o"
	@echo "... src/io_manager.i"
	@echo "... src/io_manager.s"
	@echo "... src/pico_png.o"
	@echo "... src/pico_png.i"
	@echo "... src/pico_png.s"
	@echo "... src/sprite.o"
	@echo "... src/sprite.i"
	@echo "... src/sprite.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

